name: Daily PTT Forecast

on:
  schedule:
    - cron: '0 1 * * *'  # เวลาไทย 08:00 (เพราะ GitHub ใช้ UTC+0)
  workflow_dispatch:

jobs:
  forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run PTT forecast script
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python ptt_forecast.py
